---
title: Union
description: Comparison of union elections across international unions
hide-description: true
---



## Last Year of Private Union Elections


```{r}

library(tidyverse)
library(gt)
library(here)
dt <- read_csv(here("gen", "data", 
  "cleaned_data.csv")
)

dt <- dt |> mutate(National=ifelse(National=="","Uncoded", National)) |> 
    mutate(National = ifelse(National_Count >1 , "Multiple", National))

all_unions <- sort(unique(dt$National))


```

::: {.panel-tabset}

## Filed in Last Year
```{r}
dt |> arrange(desc(Date_Filed)) |> 
    mutate(National=factor(National, levels=all_unions)) |> 
    distinct() |> 
    filter( `Case_Type`=="RC" & (`Date_Filed`  > (today() - years(1))))  |> 
    group_by(National) |> 
    summarize( "Closed Elections"=sum(!is.na(Date_Closed)), 
            "Unions Certified"=sum(Union_Cer=="Yes"), 
            "Percent Certified"=`Unions Certified`/`Closed Elections`, 
            "Median Succesful BU"=median(Num_Eligible_Voters[Union_Cer=="Yes"], na.rm=T), 
            "Total Workers Unionized"=sum(Num_Eligible_Voters[Union_Cer=="Yes"], na.rm=T)) |>
    complete(National, 
            fill=list("Open Elections"=0, 
                        "Closed Elections"=0, 
                        "Unions Certified"=0)   ) |> 
    gt() |> 
    fmt_percent(columns=`Percent Certified`, decimals=1) |> 
    fmt_integer(columns=`Total Workers Unionized`) |> 
    sub_missing(missing_text="-") |> 
    sub_zero(columns=`Percent Certified`:`Total Workers Unionized`, 
            zero_text="-") |>
    opt_interactive(use_pagination=FALSE)

```


## Voted in Last Year
```{r}
dt |> arrange(desc(Tally_Date)) |> 
    mutate(National=factor(National, levels=all_unions)) |> 
    distinct() |> 
    filter( `Case_Type`=="RC" & (`Tally_Date`  > (today() - years(1))))  |> 
    group_by(National) |> 
    summarize("Open Elections"=sum(is.na(Date_Closed)), 
            "Closed Elections"=sum(!is.na(Date_Closed)), 
            "Unions Certified"=sum(Union_Cer=="Yes"), 
            "Percent Certified"=`Unions Certified`/`Closed Elections`, 
            "Median Succesful BU"=median(Num_Eligible_Voters[Union_Cer=="Yes"], na.rm=T), 
            "Total Workers Unionized"=sum(Num_Eligible_Voters[Union_Cer=="Yes"], na.rm=T)) |>
    complete(National, 
            fill=list("Open Elections"=0, 
                    "Closed Elections"=0, 
                    "Unions Certified"=0)   ) |> 
    gt() |> 
    fmt_percent(columns=`Percent Certified`, decimals=1) |> 
    fmt_integer(columns=`Total Workers Unionized`) |> 
    sub_missing(missing_text="-") |> 
    sub_zero(columns=`Percent Certified`:`Total Workers Unionized`, 
            zero_text="-") |> 
        opt_interactive(use_pagination=FALSE)


```


## Closed in Last Year
```{r}
dt |> arrange(desc(Date_Closed)) |> 
    mutate(National=factor(National, levels=all_unions)) |> 
    distinct() |> 
    filter( `Case_Type`=="RC" & (`Date_Closed`  > (today() - years(1))))  |> 
    group_by(National) |> 
    summarize("Open Elections"=sum(is.na(Date_Closed)), 
            "Closed Elections"=sum(!is.na(Date_Closed)), 
            "Unions Certified"=sum(Union_Cer=="Yes"), 
            "Percent Certified"=`Unions Certified`/`Closed Elections`, 
            "Median Succesful BU"=median(Num_Eligible_Voters[Union_Cer=="Yes"], na.rm=T), 
            "Total Workers Unionized"=sum(Num_Eligible_Voters[Union_Cer=="Yes"], na.rm=T)) |>
    complete(National, 
            fill=list("Open Elections"=0, 
                        "Closed Elections"=0, 
                        "Unions Certified"=0)   ) |> 
    gt() |> 
    fmt_percent(columns=`Percent Certified`, decimals=1) |> 
    fmt_integer(columns=`Total Workers Unionized`) |> 
    sub_missing(missing_text="-") |> 
    sub_zero(columns=`Percent Certified`:`Total Workers Unionized`, 
            zero_text="-") |>
    opt_interactive(use_pagination=FALSE)


```

:::
