project:
  type: reporting-website

website:
  title: "Union Elections"
  open-graph: true
  navbar: 
    left: 
      - text: "Home"
        file: index.qmd
      - text: "Starbucks"
        file: content/data/starbucks/index.qmd
      - sidebar:states
      - sidebar:info


  sidebar:
    - href: index.qmd
      text: Home
    - id: states
      title: States
      href: content/data/states/index.qmd
      contents: content/data/states/*
    - id: info
      title: Info
      contents: content/data/info/*

knitr:
    opts_chunk: 
        dev: "svg"

format:
  html:
    theme: 
      - cosmo
      - custom.scss
    toc: true
    fig-width: 12
    fig-height: 9
    page-layout: full
    grid:
      sidebar-width: 300px
      body-width: 1200px
      margin-width: 300px
      gutter-width: 1.5rem
    toc-location: left

execute: 
  echo: false
  warning: false