project:
  type: reporting-website

website:
  title: "Union Elections"
  open-graph: true
  twitter-card: true
  sidebar:
    collapse-level: 1
    contents: 
      - href: index.qmd
        text: Home
      - href: content/data/starbucks/index.qmd
        text: Starbucks Elections
      - section: States
        href: content/data/states/index.qmd
        contents: content/data/states/*
      - section: Unions
        href: content/data/union/index.qmd
        contents: content/data/union/*
      - section: Yearly Reports
        contents: content/data/reports/*
      - section: Info
        contents: content/data/info/*

knitr:
    opts_chunk: 
        dev: "svg"

format:
  html:
    theme: 
      - cosmo
      - custom.scss
    toc: true
    fig-width: 12
    fig-height: 9
    page-layout: full
    grid:
      sidebar-width: 300px
      body-width: 1200px
      margin-width: 300px
      gutter-width: 1.5rem
    toc-location: right
    author-meta: Kevin Reuning

execute: 
  echo: false
  warning: false