project:
  type: reporting-website

website:
  title: "Union Elections"
  open-graph: true
  twitter-card: true
  site-url: "https://unionelections.org"
  sidebar:
    collapse-level: 1
    contents: 
      - href: index.qmd
        text: Home
      - href: data/starbucks/index.qmd
        text: Starbucks Elections
      - section: States
        href: data/states/index.qmd
        contents: data/states/*/*
      - section: Unions
        href: data/union/index.qmd
        contents: data/union/*/*
      - section: Yearly Reports
        contents: data/reports/*/*
      - section: Info
        contents: data/info/*

knitr:
    opts_chunk: 
        dev: "svg"

format:
  html:
    theme: 
      - cosmo
      - custom.scss
    toc: true
    fig-width: 12
    fig-height: 9
    page-layout: full
    grid:
      sidebar-width: 300px
      body-width: 1200px
      margin-width: 300px
      gutter-width: 1.5rem
    toc-location: right
    author-meta: Kevin Reuning
    include-in-header: 
      - text: '<script defer data-domain="unionelections.org" src="https://plausible.io/js/script.js"></script>'

execute: 
  echo: false
  warning: false
  freeze: true