project:
  type: reporting-website

website:
  title: "Union Elections"
  open-graph: true
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: cosmo
    toc: true