baseURL = "https://unionelections.org/"
languageCode = "en-us"
title = "Union Election Data"
images = ["/data/national/map.png"]

enableRobotsTXT = true
disableKinds = ['taxonomy', 'taxonomyTerm']

[Author]
  name = "Kevin Reuning"

[params]
  description = "Data on union elections in the United States"
  BookToC = true
  BookSection = "data"
  BookComments = false


[markup.tableOfContents]
  startLevel = 3
