baseURL = "https://amazing-mayer-87367c.netlify.app/"
languageCode = "en-us"
title = "Union Election Data"

[params]
  BookToC = true
  BookSection = "data"

[markup.tableOfContents]
  startLevel = 3
