---
title: Updates to Data
---

- **2024-06-26:** Added notes on the states and union pages about what event was used to record the "date" for different plots. Notes are in the raw data tables for now. Also updated them to start 2020-01-01 instead of 1999-01-01 (the data was missing pre-2000). 

- **2024-05-11**: Data now includes any RM petitions filed after August 25, 2023. These petitions are filed under the new [Cemex](https://www.nlrb.gov/news-outreach/news-story/board-issues-decision-announcing-new-framework-for-union-representation) decision which provides an alternative avenue for unionization. Under *Cemex* a union can ask for recognition "on the basis that a majority of employees in an appropriate bargaining unit have designated the union as their representative." Employers can then " either recognize and bargain with the union or promptly file an RM petition seeking an election." Currently I am unaware of anyway to track employee asks for recognition that are accepted by the employer.