name: Build and deploy
on:
  push:
    branches: main
jobs:
  build:
    runs-on: ubuntu-18.04
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      GEOCODIO_API_KEY: ${{secrets.GEOCODIO_API_KEY}}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y libgeos-dev libudunits2-dev libgdal-dev libcurl4-openssl-dev

      - name: Setup R
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: 4.0.2

      - name: Cache packages
        uses: actions/cache@v2
        with:
          path: ~/.local/share/renv
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-

      - name: Restore packages
        shell: Rscript {0}
        run: |
          if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
          renv::restore()

      - name: Build Plots and Pages
        run: |
          Rscript gen/scripts/Init.R
          Rscript gen/scripts/Mapping.R

      - name: Push to current
        id: commit
        uses: EndBug/add-and-commit@v7
        with:
          add: .
          message: 'Committed updated files'

      - name: Checkout production
        if: ${{ steps.commit.outputs.committed == 'true' }}
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
          ref: 'production'
          clean: false

      - name: Push to production
        if: ${{ steps.commit.outputs.committed == 'true' }}
        uses: EndBug/add-and-commit@v7 # You can change this to use a specific version
        with:
          add: .
          branch: "production"
          message: 'Pushed new production'
