name: Build and deploy
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-18.04
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      GEOCODIO_API_KEY: ${{secrets.GEOCODIO_API_KEY}}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          lfs: 'true'
          submodules: true
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y libgeos-dev libudunits2-dev libgdal-dev libcurl4-openssl-dev webp

      - name: Setup R
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: 4.1.2

      - name: Cache packages
        uses: actions/cache@v2
        with:
          path: ~/.local/share/renv
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-

      - name: Restore packages
        shell: Rscript {0}
        run: |
          if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
          renv::restore()

      - name: Build Plots and Pages
        run: |
          Rscript gen/scripts/Init.R
          Rscript gen/scripts/Mapping.R
          git ls-files -m | grep '\.png$' | xargs -n 1 sh -c 'cwebp -quiet $1 -o "${1%.png}.webp"' _
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Updated Plots"
          git push
          git checkout production
          git merge main
          git push
